### ISSUE TITLE
Aqueduct Issue

### ISSUE THREAD

**Issue by NTMS2017** [leocavalcante/encrypt#4]
Hi Leo,

In Dart console app Salsa20 (Stream Cipher) works as expected. I try to add in my aqueduct project (pub spec.yaml) and I try to use pub get and fails for deflectable of dependance.....

**My pub spec.yaml**
```yaml
name: niyazibankapi
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  aqueduct: ^3.0.0-beta.1
  encrypt: ^0.2.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0-beta.1
dependency_overrides:
  aqueduct:
    path:  /Users/niyazitoros/aqueduct/aqueduct/
  aqueduct_test:
    path:  /Users/niyazitoros/aqueduct/aqueduct_test/
```

**And the ERROR:**

```shell
Niyazis-MacBook-Pro:niyazibankapiniyazitoros$ pub get
Resolving dependencies... (2.5s)
Because reflectable >=2.0.0 depends on analyzer ^0.31.0 and reflectable >=1.0.4 <=2.0.0-dev.1.0 depends on analyzer ^0.30.0, reflectable >=1.0.4 requires analyzer ^0.30.0 or ^0.31.0.
And because reflectable >=1.0.1 <1.0.4 depends on analyzer >=0.27.2 <0.30.0 and every version of aqueduct from path depends on analyzer ^0.32.0, aqueduct from path is incompatible with reflectable >=1.0.1.
And because every version of encrypt depends on pointycastle ^1.0.0-rc2 which depends on reflectable >=1.0.1 <3.0.0, aqueduct from path is incompatible with encrypt.
So, because niyazibankapidepends on both encrypt ^0.2.0 and aqueduct from path, version solving failed.
Niyazis-MacBook-Pro:niyazibankapiniyazitoros$ 
```
